import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui";

// Local Fonts
const coreSansC = localFont({
  src: [
    {
      path: "../public/fonts/Core-Sans-C-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Core-Sans-C-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Core-Sans-C-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-core-sans-c",
  display: "swap",
});

const causten = localFont({
  src: [
    {
      path: "../public/fonts/Causten-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Causten-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Causten-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Causten-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Causten-Light.otf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-causten",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`${coreSansC.variable} ${causten.variable} overflow-y-scroll antialiased`}
        suppressHydrationWarning
      >
        <main className="mx-auto min-h-screen flex flex-col bg-background">
          {children}
        </main>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
